### PR TITLE
Distributive instances for ((->) e) and ReaderT

### PR DESCRIPTION
**Pull request by freebroccolo**

### CODE REVIEW

**Comment by garyb** [comment]
Oops, it seems I wasn't watching this repo so didn't get notified. Looks good, but can we flip the dependencies and have `transformers` pull `distributive` in, and define the `Distributive ReaderT` instance in there instead?

**Comment by freebroccolo** [comment]
@garyb no worries. Putting the instances in `transformers` sounds reasonable I think.

**Comment by garyb** [comment]
Closing this as the `(->)` instance has now been added here, and `ReaderT` in `transformers`. Thanks!

**Comment by freebroccolo** [comment]
:+1:

**Pull request closed without merging**
